### ISSUE TITLE
sbt spends most time resolving packages from com.github.fommil.netlib

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#146]
Makes compilation unnecessarily slow.

**Comment by rockt** [comment]
Fixed this. Netlib is imported by Breeze when using the `"org.scalanlp" %% "breeze-natives" % "0.8.1"` sbt dependency. Note that a user might want to include this dependency, because it supposedly speeds up Breeze quite a bit (by using BLAS/LAPACK/ARPACK). Standard Breeze still depends on com.github.fommil.netlib:core:1.1.2, so if we want to get rid of that one as well we have to get rid of the Breeze dependency — I guess that's something we can consider, especially if we will use BIDMat in the future.

**Comment by riedelcastro** [comment]
Excellent. Yeah, we can look into this in the future, but for now I am happy to avoid this constant re-syncing.
